version: 666.{build}
skip_tags: false
os: Visual Studio 2019
clone_depth: 1
clone_folder: C:\rssguard

environment:
  QTVER: '5.14'
  QTREV: '2'
  QTDIR: 'C:\Qt\5.14.2\msvc2017_64'
  QMAKESPEC: win32-msvc
  access_token:
    secure: oR2iY1h+Z5AF4t3yP1mxNW7HL8qhPm8y4Uupp4b03QSC7puVrkkCaO1E1NQA9q9K
  matrix:
    - qmake_args: 'USE_WEBENGINE=false'
    - qmake_args: 'USE_WEBENGINE=true'

artifacts:
  - path: 'rssguard-build\src\rssguard\*win64.exe'
    name: rssguardexe

  - path: 'rssguard-build\src\rssguard\*win64.7z'
    name: rssguard7z

deploy:
  - provider: BinTray
    username: martinrotter
    api_key:
      secure: T463Ei805xAQcxqvtTu7WDsfCmhqViVTdwzPQdyXVLovhTNLR3R5ZnPXMEuGCYJY
    subject: martinrotter
    repo: rssguard
    package: Development
    version: Windows
    publish: true
    override: true
    explode: false
  - provider: GitHub
    description: 'release by appveyor'
    auth_token:
      secure: oR2iY1h+Z5AF4t3yP1mxNW7HL8qhPm8y4Uupp4b03QSC7puVrkkCaO1E1NQA9q9K
    artifact: rssguardexe, rssguard7z
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true

build_script:
  - git submodule update --init --recursive --remote
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"'
  - ps: .\resources\scripts\.appveyor-build-win.ps1
